Updated primitives link, resolves 5348
aframevr/aframe pull request #5349
Opened 2023-08-08 12:04 UTC by lainshiHenry

**Description:**
From (https://aframe.io/docs/1.4.0/guides/building-a-basic-scene.html), the "Primitives" destination link results in a 404 page.

**Changes proposed:**
- Updated building-a-basic-scene.md file -> primitives link to reflect new destination.

2023-08-08 16:08 UTC, vincentfretin requested changes
Thank you for the PR. The path is wrong though, the folder is introduction lowercase. Can you please fix it.

2023-08-08 16:13 UTC, vincentfretin commented
When you create a PR, you should reference the issue, here #5348 
In you commit message, use at the end " (fix #5348)" this will close the issue automatically when the PR is merged.
You can edit your commit like this:
```
git add -p
git commit --amend
git push --force
```

2023-08-09 11:18 UTC, lainshiHenry commented
Thanks @vincentfretin for the tips on the commits and checking my PR.

Can you take a look at this updated one?

2023-08-09 12:20 UTC, vincentfretin approved these changes
Yes, all good now. @dmarcos can merge. ;-)

2023-08-10 03:44 UTC, dmarcos commented
Thanks so much! Congrats on your first contribution 👏

2023-08-10 03:44 UTC, merged